### ISSUE TITLE
Add an idle logout warning message

### ISSUE THREAD

**Issue by ryannewington** [lithnet/idle-logoff#10]

**Comment by ryannewington** [comment]
Test build 
[lithnet.idlelogoff.setup.msi.zip](https://github.com/lithnet/idle-logoff/files/2661681/lithnet.idlelogoff.setup.msi.zip)

**Comment by ryannewington** [comment]
[lithnet.idlelogoff.setup.msi.zip](https://github.com/lithnet/idle-logoff/files/2678354/lithnet.idlelogoff.setup.msi.zip)

Updated to allow warning message interval to be configured from the UI

**Comment by brettgus** [comment]
Not sure if I should be adding a new issue for this, but FYI the beta is error out for me
Error message:
https://imgur.com/FLTRIty

**Comment by ryannewington** [comment]
@brettgus are you able to get me the rest of the information from that error message. Was there are bunch of info shown below that?

**Comment by ryannewington** [comment]
Or steps to reproduce?

**Comment by ryannewington** [comment]
@brettgus are you able to provide any more information on this issue? I've tried tracking it down, but without the full exception message and stack trace, I'm not able to find this to be able to fix it.

**Comment by gingeronabike** [comment]
Hi @ryannewington - first off, thanks for creating this little utility! It works quite well. I tested the beta version (1.1.6922) and get the same error referenced by brettgus. The logoff notification does not work. To reproduce the error message, open the Lithnet.Idlelogoff.exe file located in C:\Program Files (x86)\Lithnet\IdleLogoff. See below for the full error message. If you click "Continue", the software will continue to open.

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Value of '0' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at Lithnet.idlelogoff.FrmSettings.RefreshUI()
   at Lithnet.idlelogoff.FrmSettings.frmSettings_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
lithnet.idlelogoff
    Assembly Version: 1.1.6922.23117
    Win32 Version: 1.1.6922.23117
    CodeBase: file:///C:/Program%20Files%20(x86)/Lithnet/IdleLogoff/Lithnet.IdleLogoff.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3353.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
`

**Comment by ryannewington** [comment]
Thanks @gingeronabike, that allowed me to find the problem. I appreciate you taking the time to report the details.

Here is the latest build that should have that issue fixed now.

https://github.com/lithnet/idle-logoff/releases/tag/v1.1.6997

Do let  me know if you find any additional issues, or if it works for you. Once I have confirmation, then I will make the release as production ready.

Cheers

Ryan

**Comment by gingeronabike** [comment]
Hi @ryannewington - wow, thanks for the quick response! The popup displays correctly now, and I'm not able to replicate the previous error. I do think there's a bug though - if the idle popup appears and starts to count down - if you move the mouse, it goes away - but the next time it comes back, it resumes the countdown from where it left off. It feels like the timer should reset each time the popup is triggered.

Other suggestions:
1. Update the ADMX file / add support for customizing the timer (and possibly message text) 
2. Would probably be Windows 10 only, potentially not worth the effort, but utilizing the native Toast notifications 

Other possible bugs:
1. The "Idle session logoff" popup has a "Cancel" button, but this button is essentially useless, since the popup closes if you move the mouse. Maybe consider removing the "Cancel" button altogether?
2. The default value for triggering the notification is "0", which means you don't get one at all. Since I don't think this value can be defined by Group Policy, it doesn't really work for the way we had intended to deploy it. We would need to edit the value on each machine. Maybe make the value default to something other than zero? I guess there are arguments for either option.

**Comment by ryannewington** [comment]
@gingeronabike thanks for the feedback.

The ADMX files have been updated, and you should be seeing an option there for the warning interval

![image](https://user-images.githubusercontent.com/17229877/53453298-cad53380-3a77-11e9-83c1-03c99a9a1a5b.png)

I'm not seeing the countdown bug in my environment. Perhaps I'm testing differently to you? Can you detail your scenario

The cancel button is there so you can hit the enter key or space bar and that will close the window. Otherwise there is a short delay in pressing any other key for the window to disappear.

I made the default interval zero, just to make it the same experience for existing installations that do not want this. It's an 'opt-in' feature. However, you should be seeing the GPO option to control this.

**Comment by gingeronabike** [comment]
Hi @ryannewington 
My apologies for not checking that the ADMX files were updated with the beta installer. Everything looks good there! The explanation about the Cancel button makes sense, as does the default interval being zero. That last point isn't an issue, since the ADMX file works fine.

I will say that I'm still experiencing a bug with the timer. For example, if I define the timer as 120 seconds in Group Policy, the idle session logoff popup doesn't always start at 120 seconds. Sometimes it does, but sometimes it will start at a strange value.. like 109 seconds. Additionally, sometimes when it's counting down, it will "go back in time"... e.g. 120, 119, 118, 117, 116, 119, 118, 117..

In my testing, this happens inconsistently. It works as expected about 80% of the time.

**Comment by gingeronabike** [comment]
I tested this on a brand new machine and the timer issue still exists. The idle session logoff popup doesn't always start counting down from 120. It's really hit or miss. Again, I'd say about 20% of the time it starts counting down from, for example, 104 instead of 120.

I also observed an issue where the popup would try to appear, but close itself immediately. This cycle repeated. I also noticed that it seems like you need to move the mouse over the popup itself to reset the timer - just moving the mouse alone isn't enough. This may be expected behaviour.

We use fairly lightly customized builds of Windows. No third-party antivirus or anything like that. Let me know if you have any specific things you want me to test/try

**Comment by ryannewington** [comment]
Ok that's odd. I'll have a look into this. Can you tell me what value you are using for the idle limit, just so I'm testing the same scenario as you.

**Comment by gingeronabike** [comment]
I just looked and was using an Idle timeout value of 2 minutes, with a warning of 120 seconds ... whoops, so that may have explained when the popup would appear and close repeatedly. I changed it to a timeout value of 4 minutes, and a warning of 120 seconds before. With this configuration, I'm still sometimes seeing the idle session logoff start at a value that's less than what was configured.

**Comment by ryannewington** [comment]
Ok that makes sense. 

The start time of the warning will be up to 15 seconds past the configured time as we only check the idle status every 15 seconds. I'm working on improving things a bit here to make things a bit more intuitive.

**Comment by ryannewington** [comment]
Ok this one should be a bit better behaved. The sacrifice made here is the 15-second delay will be on the idle detection, rather than the warning message. So it can take up to 15 seconds longer for the tool to detect that the user is idle. 

Thanks again for your help testing this @gingeronabike 

[lithnet.idlelogoff.setup.msi.zip](https://github.com/lithnet/idle-logoff/files/2912866/lithnet.idlelogoff.setup.msi.zip)

**Comment by gingeronabike** [comment]
@ryannewington Just tested the latest version. The timer does seem to consistently start at 120 seconds now.

However, I'm still seeing a bug where the idle session logoff popup will rapidly appear, disappear, reappear - continuously - with the countdown still continuing. Do you want a separate bug opened for this? I'm not sure how to replicate this issue, but it seems to occur when the mouse cursor is left over where the popup appears.

**Comment by ryannewington** [comment]
@gingeronabike you theory was spot on. I was able to reproduce it if the mouse was only partially on the message box. Windows was sending 'mouse moved' events even though the mouse wasn't moving, hence the behavior you saw in your testing. I've modified the behavior a bit now, which should have that issue resolved.

I've made a couple of other changes
- In the ADMX I've split the warning message into its own policy option
- I've included the ability to customize your own warning message through GPO

[lithnet.idlelogoff.setup.msi.zip](https://github.com/lithnet/idle-logoff/files/2917600/lithnet.idlelogoff.setup.msi.zip)

Ryan

**Comment by gingeronabike** [comment]
@ryannewington I'm happy to report that I can't find any issues this time around :+1: Thanks!

**Comment by ryannewington** [comment]
Awesome @gingeronabike thanks very much for testing and helping find these issues. If there's no further issues in the next few days, I'll do an official release.

**Comment by ryannewington** [comment]
I've released this version https://github.com/lithnet/idle-logoff/releases/tag/v1.1.6999
